using UnityEngine;

namespace SOS.AndrewsAdventure.Inventory
{
    [CreateAssetMenu(fileName = "baseItem", menuName = "Andrew's Adventure/Inventory Weapon", order = 5)]
    public class WeaponItem : BaseItem
    {
        [SerializeField] int baseDamage;
    }
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             